import { useBrandTheme } from '@/hooks/useBrandTheme';

interface ExportOptions {
  title: string;
  subtitle?: string;
  dateLabel: string;
  currency?: string;
  preparerName?: string;
  notes?: string;
  businessName: string;
  htmlContent: string;
}

// Professional PDF export with business letterhead
export function exportReportAsPDF(opts: ExportOptions) {
  const { businessName, logoUrl } = useBrandTheme.getState?.() || { businessName: opts.businessName, logoUrl: null };

  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to export PDF');
    return;
  }

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${opts.title} - ${opts.businessName}</title>
      <style>
        @page { size: A4; margin: 25mm 20mm; }
        body { font-family: system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; font-size: 11pt; color: #111; line-height: 1.5; }
        .letterhead { display: flex; align-items: center; gap: 16px; border-bottom: 3px solid #0f172a; padding-bottom: 16px; margin-bottom: 24px; }
        .logo { max-height: 48px; max-width: 140px; object-fit: contain; }
        .company { flex: 1; }
        .company-name { font-size: 18pt; font-weight: 700; color: #0f172a; }
        .meta { font-size: 9pt; color: #475569; }
        h1 { font-size: 16pt; margin: 0 0 4px 0; color: #0f172a; }
        .report-meta { display: flex; gap: 24px; margin-bottom: 24px; font-size: 9pt; color: #475569; }
        .notes { margin-top: 32px; padding: 16px; background: #f8fafc; border-left: 4px solid #64748b; font-size: 10pt; }
        .footer { margin-top: 40px; font-size: 8pt; color: #64748b; text-align: center; border-top: 1px solid #e2e8f0; padding-top: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 6px 8px; text-align: left; border-bottom: 1px solid #e2e8f0; }
        th { background: #f1f5f9; font-weight: 600; }
        .total-row { font-weight: 700; background: #f8fafc; }
        @media print {
          .no-print { display: none; }
        }
      </style>
    </head>
    <body>
      <div class="letterhead">
        ${logoUrl ? `<img src="${logoUrl}" class="logo" alt="Logo">` : ''}
        <div class="company">
          <div class="company-name">${businessName}</div>
          <div class="meta">Financial Report • ${opts.currency || 'MWK'}</div>
        </div>
        <div style="text-align:right; font-size:9pt; color:#64748b;">
          Generated: ${new Date().toLocaleDateString('en-MW')}
        </div>
      </div>

      <h1>${opts.title}</h1>
      ${opts.subtitle ? `<p style="margin:4px 0 16px; color:#475569;">${opts.subtitle}</p>` : ''}

      <div class="report-meta">
        <div><strong>Date:</strong> ${opts.dateLabel}</div>
        ${opts.preparerName ? `<div><strong>Prepared by:</strong> ${opts.preparerName}</div>` : ''}
        <div><strong>Currency:</strong> ${opts.currency || 'MWK'}</div>
      </div>

      ${opts.htmlContent}

      ${opts.notes ? `
        <div class="notes">
          <strong>Notes & Disclosures</strong><br>
          ${opts.notes.replace(/\n/g, '<br>')}
        </div>
      ` : ''}

      <div class="footer">
        This document was generated by Ledgr • Confidential
      </div>

      <script>
        setTimeout(() => { window.print(); }, 300);
      </script>
    </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
}

// Basic XBRL export (IFRS taxonomy stub)
export function exportReportAsXBRL(opts: ExportOptions & { 
  facts: Array<{ concept: string; value: number; unit?: string; date?: string }> 
}) {
  const xbrl = `<?xml version="1.0" encoding="UTF-8"?>
<xbrli:xbrl xmlns:xbrli="http://www.xbrl.org/2003/instance"
            xmlns:ledgr="http://ledgr.app/xbrl/2026"
            xmlns:iso4217="http://www.xbrl.org/2003/iso4217"
            xmlns:xlink="http://www.w3.org/1999/xlink"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

  <xbrli:context id="current">
    <xbrli:entity>
      <xbrli:identifier scheme="http://www.ledgr.app">${opts.businessName}</xbrli:identifier>
    </xbrli:entity>
    <xbrli:period>
      <xbrli:instant>${opts.dateLabel}</xbrli:instant>
    </xbrli:period>
  </xbrli:context>

  <xbrli:unit id="MWK">
    <xbrli:measure>iso4217:MWK</xbrli:measure>
  </xbrli:unit>

  <!-- Facts -->
  ${opts.facts.map(fact => `
  <ledgr:${fact.concept} contextRef="current" unitRef="${fact.unit || 'MWK'}" 
    ${fact.date ? `decimals="2"` : ''}>${fact.value}</ledgr:${fact.concept}>`).join('\n')}

  <!-- Notes -->
  ${opts.notes ? `
  <ledgr:Notes contextRef="current">${opts.notes}</ledgr:Notes>` : ''}

</xbrli:xbrl>`;

  const blob = new Blob([xbrl], { type: 'application/xml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${opts.title.toLowerCase().replace(/\s+/g, '-')}-${opts.dateLabel}.xbrl`;
  a.click();
  URL.revokeObjectURL(url);
}
