import { serve } from 'https://deno.land/std@0.177.0/http/server.ts';
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
// Invoke daily from Supabase Cron with `x-cron-secret`; sends are deliberately
// idempotent: an event for a stage/date prevents duplicate reminders.
serve(async req => { try { const CRON_SECRET = Deno.env.get('INVOICE_CRON_SECRET'); if(!CRON_SECRET || req.headers.get('x-cron-secret') !== CRON_SECRET) throw new Error('Unauthorised'); const db=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!); const today=new Date().toISOString().slice(0,10); const {data: invoices}=await db.from('invoices').select('id,business_id,due_date,invoice_number,total_amount,amount_paid,contacts(email,name)').in('status',['sent','viewed','overdue','partially_paid']).not('due_date','is',null); let reminders=0;
for(const inv of invoices||[]){ const days=Math.floor((Date.now()-new Date(inv.due_date).getTime())/86400000); const stage=days===0?'due':days===3?'3_days':days===7?'7_days':days===14?'14_days':null; if(!stage) continue; const {data: sent}=await db.from('invoice_delivery_events').select('id').eq('invoice_id',inv.id).eq('event_type','reminder').eq('reminder_stage',stage).limit(1); if(sent?.length) continue; await db.from('invoice_delivery_events').insert({business_id:inv.business_id,invoice_id:inv.id,event_type:'reminder',reminder_stage:stage,metadata:{scheduled_for:today,tone:days>=14?'final':days>=7?'urgent':days>=3?'firm':'friendly'}}); await db.from('invoices').update({status:days>0?'overdue':inv.status} as never).eq('id',inv.id); reminders++; }
// Recurring rows are materialised as copies; a worker/admin completes delivery where a recipient is available.
const {data: recurring}=await db.from('recurring_invoices').select('*').eq('active',true).lte('next_run_date',today); for(const r of recurring||[]){ const {data:t}=await db.from('invoices').select('*').eq('id',r.template_invoice_id).single(); if(!t) continue; const next=new Date(`${r.next_run_date}T00:00:00Z`); next.setMonth(next.getMonth()+(r.frequency==='quarterly'?3:1)); const {invoice_number:tplNumber,...rest}=t; const copy:Record<string,unknown>={...rest}; for(const k of ['id','created_at','updated_at','sent_at','viewed_at','amount_paid','journal_entry_id','credit_note_for','amount_due']){delete copy[k];} await db.from('invoices').insert({...copy,invoice_number:`${tplNumber}-R${today.replaceAll('-','')}`,issue_date:today,due_date:today,status:'draft',amount_paid:0,created_at:undefined} as never); await db.from('recurring_invoices').update({next_run_date:next.toISOString().slice(0,10)}).eq('id',r.id); }
return Response.json({reminders}); }catch(e){return new Response(JSON.stringify({error:e instanceof Error?e.message:'error'}),{status:401})} });
