// supabase/functions/_shared/sanitiseHtml.ts
//
// HTML sanitiser for email bodies generated by send-invoice. Allows only safe
// structural tags and strips everything else. This is not a full DOMPurify
// replacement but is sufficient for the controlled email body content Ledgr
// generates. Anything that could execute script (script tags, event
// handlers, javascript: URIs, iframes, objects, embeds, forms) is removed
// entirely.
//
// Uses only string/RegExp APIs, so it is unit-testable under Node/vitest
// (see _shared/__tests__/sanitiseHtml.test.ts).

const ALLOWED_TAGS = new Set([
  'p', 'br', 'b', 'i', 'u', 'strong', 'em', 'h1', 'h2', 'h3', 'h4',
  'ul', 'ol', 'li', 'table', 'thead', 'tbody', 'tr', 'th', 'td',
  'div', 'span', 'hr', 'blockquote', 'a', 'img',
]);

const ALLOWED_ATTRS: Record<string, Set<string>> = {
  a: new Set(['href', 'style']),
  img: new Set(['src', 'alt', 'width', 'height', 'style']),
  td: new Set(['style', 'colspan', 'rowspan']),
  th: new Set(['style', 'colspan', 'rowspan']),
  '*': new Set(['style']),
};

export function sanitiseHtml(html: string): string {
  // Remove script/style/iframe/object/embed/form tags and their content
  let clean = html.replace(/<(script|style|iframe|object|embed|form|textarea|input|button|select)[^>]*>[\s\S]*?<\/\1>/gi, '');
  // Remove self-closing dangerous tags
  clean = clean.replace(/<(script|style|iframe|object|embed|form|textarea|input|button|select)[^>]*\/?>/gi, '');
  // Remove event handler attributes (onclick, onerror, onload, etc.)
  clean = clean.replace(/\s+on\w+\s*=\s*("[^"]*"|'[^']*'|[^\s>]*)/gi, '');
  // Remove javascript: and data: URIs in href/src attributes
  clean = clean.replace(/(href|src)\s*=\s*["']?\s*(javascript|data|vbscript)\s*:/gi, '$1="removed:');
  // Strip tags not in the allowlist
  clean = clean.replace(/<\/?([a-zA-Z][a-zA-Z0-9]*)\b[^>]*>/g, (match, tag) => {
    const lower = tag.toLowerCase();
    if (!ALLOWED_TAGS.has(lower)) return '';
    // For allowed tags, strip disallowed attributes
    if (match.startsWith('</')) return `</${lower}>`;
    const attrRegex = /([a-zA-Z-]+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g;
    const safeAttrs: string[] = [];
    let m: RegExpExecArray | null;
    while ((m = attrRegex.exec(match)) !== null) {
      const attrName = m[1].toLowerCase();
      const attrVal = m[2] ?? m[3] ?? m[4] ?? '';
      const allowed = ALLOWED_ATTRS[lower] ?? new Set<string>();
      const globalAllowed = ALLOWED_ATTRS['*'];
      if (allowed.has(attrName) || globalAllowed.has(attrName)) {
        // Block javascript: in href/src values
        if ((attrName === 'href' || attrName === 'src') && /^\s*(javascript|data|vbscript)\s*:/i.test(attrVal)) {
          continue;
        }
        safeAttrs.push(`${attrName}="${attrVal.replace(/"/g, '&quot;')}"`);
      }
    }
    const selfClosing = match.endsWith('/>');
    return `<${lower}${safeAttrs.length ? ' ' + safeAttrs.join(' ') : ''}${selfClosing ? ' /' : ''}>`;
  });
  return clean;
}
