import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { supabase } from '@/lib/supabase';
import { AuthShell } from '@/components/auth/AuthShell';
import { FormField, Input, OTPInput, AuthAlert, SubmitButton } from '@/components/auth/AuthUI';
export function ForgotPasswordPage(){const {t}=useTranslation();const navigate=useNavigate();const [email,setEmail]=useState('');const [code,setCode]=useState('');const [step,setStep]=useState<'email'|'code'>('email');const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);
 async function submit(e:FormEvent){e.preventDefault();setError(null);setLoading(true);if(step==='email'){const {error}=await supabase.auth.resetPasswordForEmail(email);if(!error)setStep('code');else setError(error.message)}else{const {error}=await supabase.auth.verifyOtp({email,token:code,type:'recovery'});if(!error)navigate('/reset-password');else setError('That code is invalid or expired.')}setLoading(false)}
 return <AuthShell title={step==='email'?t('auth.resetPassword'):'Enter your reset code'} subtitle={step==='email'?t('auth.resetPasswordSubtitle'):'Check your email for the six-digit code.'}><form onSubmit={submit} className="space-y-4">{error&&<AuthAlert type="error" message={error}/>} {step==='email'?<FormField id="email" label={t('common.email')}><Input id="email" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@business.mw"/></FormField>:<><p className="text-sm text-gray-500">Code sent to {email}</p><OTPInput value={code} onChange={setCode} disabled={loading}/></>}<SubmitButton loading={loading} label={step==='email'?'Send reset code':'Verify code'} loadingLabel={t('auth.sending')}/></form><p className="mt-5 text-center text-sm text-gray-500"><Link to="/login" className="font-medium text-brand-600">{t('auth.backToSignIn')}</Link></p></AuthShell>}
