// supabase/functions/invoice-open/index.ts
//
// Tracking pixel endpoint — embedded in invoice emails so Ledgr can record
// when a recipient opens the message.
//
// Security:
//   The pixel URL carries two query parameters:
//     ?invoice=<uuid>&token=<hmac>
//   where `token` = HMAC-SHA256(invoiceId, INVOICE_TRACKING_SECRET).
//   The token is generated by send-invoice at send time and verified here.
//   Without a valid token the request is silently ignored (we still return
//   the 1×1 GIF so the email client doesn't show a broken-image icon, but
//   no database write occurs).
//
//   This prevents:
//     - Unauthenticated invoice UUID enumeration
//     - Forged "viewed" status updates
//     - Fake invoice_delivery_events rows

import { serve } from 'https://deno.land/std@0.224.0/http/server.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';

const SUPABASE_URL = Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE_KEY = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;

// 1×1 transparent GIF (smallest valid GIF)
const PIXEL = Uint8Array.from(
  atob('R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw=='),
  (c) => c.charCodeAt(0),
);

const GIF_HEADERS = {
  'Content-Type': 'image/gif',
  'Cache-Control': 'no-store, no-cache, must-revalidate, max-age=0',
  'Pragma': 'no-cache',
  'Expires': '0',
};

async function hmacSha256Hex(secret: string, payload: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  );
  const sig = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(payload));
  return Array.from(new Uint8Array(sig)).map((b) => b.toString(16).padStart(2, '0')).join('');
}

function timingSafeEqual(a: string, b: string): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) diff |= a.charCodeAt(i) ^ b.charCodeAt(i);
  return diff === 0;
}

serve(async (req) => {
  // Always return the pixel — never leak whether the invoice exists or
  // the token is valid via HTTP status codes or response size.
  const pixelResponse = () => new Response(PIXEL, { headers: GIF_HEADERS });

  try {
    const url = new URL(req.url);
    const invoiceId = url.searchParams.get('invoice');
    const token = url.searchParams.get('token');

    if (!invoiceId || !token) return pixelResponse();

    // Verify the HMAC token
    const secret = Deno.env.get('INVOICE_TRACKING_SECRET') || Deno.env.get('CRON_SECRET') || '';
    if (!secret) {
      // Secret not configured — cannot verify tokens, silently ignore
      console.warn('invoice-open: INVOICE_TRACKING_SECRET not configured, ignoring open event.');
      return pixelResponse();
    }

    const expected = await hmacSha256Hex(secret, invoiceId);
    if (!timingSafeEqual(expected, token)) {
      // Invalid token — forged or tampered request, silently ignore
      return pixelResponse();
    }

    // Token is valid — record the open event using service role
    const db = createClient(SUPABASE_URL, SERVICE_ROLE_KEY, { auth: { persistSession: false } });

    const { data } = await db
      .from('invoices')
      .select('business_id, viewed_at')
      .eq('id', invoiceId)
      .is('deleted_at', null)
      .maybeSingle();

    if (!data) return pixelResponse();

    // Only set viewed_at on first open (don't overwrite the original timestamp)
    if (!data.viewed_at) {
      await db
        .from('invoices')
        .update({ viewed_at: new Date().toISOString(), status: 'viewed' } as never)
        .eq('id', invoiceId);
    }

    await db.from('invoice_delivery_events').insert({
      invoice_id: invoiceId,
      business_id: data.business_id,
      event_type: 'opened',
    } as never);

    return pixelResponse();
  } catch {
    return pixelResponse();
  }
});
