#!/usr/bin/env python3
"""Render docs/database/staging-schema-inventory.md from the live inventory JSON."""
import json
import os

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
INV = json.load(open(os.path.join(REPO, 'artifacts/database/staging-schema-inventory.json')))
OUT = os.path.join(REPO, 'docs/database/staging-schema-inventory.md')

L = []
A = L.append
A("# Ledgr — Staging Schema Inventory (Phase 8A.1) — AUTHORITATIVE (live capture)")
A("")
A(f"> **Status: LIVE CAPTURE.** Built from the read-only Management API capture of")
A(f"> project `{INV['meta']['capture_status'].split('project ')[-1].split(' ')[0] if 'project ' in INV['meta']['capture_status'] else ''}`")
A(f"> ({INV['meta']['capture_status']}).")
A("")
A(f"- PostgreSQL version (live): **{INV['meta']['postgres_version']}**")
A(f"- Generated: {INV['meta']['generated_at']}")
A(f"- Capture files: {', '.join(INV['meta']['capture_files'])}")
A("")
cs = INV['classification_summary']
A("## Classification summary")
A("")
A(f"- Tables: **{cs['tables_total']}** ({cs['tables_match']} match repository migrations)")
A(f"- Enums: **{cs['enums_total']}**; base enums missing from repo: {len(cs['enums_base_missing_from_repo'])}")
A(f"- Functions: **{cs['functions_total']}**; missing from repo: {len(cs['functions_missing_from_repo'])}")
A(f"- Views: **{cs['views_total']}**; missing from repo: {len(cs['views_missing_from_repo'])}")
A(f"- Policies: **{cs['policies_total']}** across {len(INV['policies_by_table'])} tables")
A(f"- **Tables with RLS enabled but NO policies (deny-all): {len(cs['rls_enabled_no_policies'])}**")
A(f"- Storage buckets: {len(cs['storage_buckets'])}")
A(f"- Cron jobs: {len(cs['cron_jobs'])}")
A("")
A("## Schemas")
A("")
A("`" + "`, `".join(INV['schemas']) + "`")
A("")
A("## Extensions")
A("")
A("| Extension | Version | Schema |")
A("|---|---|---|")
for e in INV['extensions']:
    A(f"| {e['extname']} | {e['extversion']} | {e['schema']} |")
A("")
A("## Enums")
A("")
A("| Enum | Labels (live order) | Classification |")
A("|---|---|---|")
for ename, e in INV['enums'].items():
    A(f"| {ename} | {', '.join(e['labels'])} | {e['classification']} |")
A("")
A("## Tables")
A("")
for tname, t in INV['tables'].items():
    A(f"### `{tname}` — {t['classification']}")
    A("")
    A("| Column | Type | Not null | Default | Identity | Generated |")
    A("|---|---|---|---|---|---|")
    for cname, c in t['columns'].items():
        A(f"| {cname} | `{c['pg_type']}` | {c['not_null']} | `{c['default'] or '—'}` | {c['identity'] or '—'} | {c['generated'] or '—'} |")
    A("")
    A("---")
    A("")
A("## Constraints")
A("")
A(f"- Primary keys: {len(INV['primary_keys'])}")
A(f"- Foreign keys: {len(INV['foreign_keys'])}")
A(f"- Unique constraints: {len(INV['unique_constraints'])}")
A(f"- Check constraints: {len(INV['check_constraints'])}")
A(f"- Indexes: {len(INV['indexes'])}")
A(f"- Generated columns: {len(INV['generated_columns'])}")
A(f"- Identity columns: {len(INV['identity_columns'])}")
A(f"- Sequences: {len(INV['sequences'])}")
A("")
A("## Views")
A("")
for v in INV['views']:
    A(f"### `{v['name']}` — {v['classification']}")
    A("")
    A("```sql")
    A(v['definition'])
    A("```")
    A("")
A("## Functions (RPCs)")
A("")
for f in INV['functions']:
    A(f"### `{f['signature']}` — {f['classification']}")
    A("")
    A(f"- Volatility: `{f['volatility']}` · Security definer: `{f['security_definer']}` · Owner: `{f['owner']}` · Search path: `{f['search_path']}`")
    A("")
    A("```sql")
    A(f['definition'])
    A("```")
    A("")
A("## Triggers")
A("")
A("| Trigger | Table | Definition |")
A("|---|---|---|")
for t in INV['triggers']:
    A(f"| {t['tgname']} | {t['relname']} | `{t['pg_get_triggerdef']}` |")
A("")
A("## RLS")
A("")
A(f"- Tables with RLS: {sum(1 for r in INV['rls'] if r['relrowsecurity'])}/{len(INV['rls'])} · Forced: {sum(1 for r in INV['rls'] if r['relforcerowsecurity'])}")
A("")
A("### Policies by table")
A("")
A("| Table | Policies |")
A("|---|---|")
for t in sorted(INV['policies_by_table']):
    A(f"| {t} | {', '.join(INV['policies_by_table'][t])} |")
A("")
A("### RLS enabled but NO policies (deny-all)")
A("")
A("The following tables have RLS enabled and no policies — every authenticated")
A("query is denied (zero rows):")
A("")
for t in INV['rls_enabled_no_policies']:
    A(f"- `{t}`")
A("")
A("## Storage")
A("")
A(f"- Buckets: {len(INV['storage']['buckets'])} — {', '.join(b['id'] for b in INV['storage']['buckets']) or '(none — buckets are dashboard-created and were not migrated)'}")
A(f"- Storage policies: {len(INV['storage']['policies'])}")
A("")
A("## Cron jobs")
A("")
A("| Job id | Schedule | Active | Command |")
A("|---|---|---|---|")
for j in INV['cron_jobs']:
    A(f"| {j['jobid']} | `{j['schedule']}` | {j['active']} | `{(j['command'] or '')[:100]}` |")
A("")
A("## Known gaps (confirmed against live staging)")
A("")
A("1. **9 RPCs missing from both repository and staging** (they exist only on the")
A("   legacy/production database; bodies were never version-controlled):")
for s in cs['known_rpcs_missing_everywhere']:
    A(f"   - `{s}`")
A("2. **4 views missing from both repository and staging** (exist only on the")
A("   legacy/production database):")
for v in cs['known_views_missing_everywhere']:
    A(f"   - `{v}`")
A("3. **RLS policies for {len(cs['rls_enabled_no_policies'])} tables** — RLS enabled,")
A("   zero policies (deny-all). The legacy database had out-of-band policies that")
A("   were never migrated. The app is not functional on a fresh environment until")
A("   these are reconstructed (Phase 8B scope).")
A("4. **Storage buckets** — `business-logos` / `user-exports` are dashboard-created")
A("   and absent from a fresh environment; recreate per environment.")
A("")
A("## Source of truth")
A("")
A("Machine-readable form: `artifacts/database/staging-schema-inventory.json`.")
A("Capture tooling: `scripts/database/capture-staging-schema-via-api.sh`.")
A("Builder: `scripts/database/build-live-inventory.py`.")
A("")

with open(OUT, 'w') as f:
    f.write("\n".join(L))
print('wrote', OUT, f'({len(L)} lines)')
