-- ─────────────────────────────────────────────────────────────────────────────
-- Public API + Webhooks foundation
-- ─────────────────────────────────────────────────────────────────────────────

create extension if not exists pgcrypto;

-- API keys are generated by the create-api-key Edge Function. Only the hash is
-- stored; the raw ledgr_sk_... secret is returned once to the user.
create table if not exists public.api_keys (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  name text not null,
  key_hash text not null unique,
  key_prefix text not null,
  last_used_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create index if not exists idx_api_keys_business on public.api_keys(business_id, created_at desc);
create index if not exists idx_api_keys_active_hash on public.api_keys(key_hash) where revoked_at is null;

alter table public.api_keys enable row level security;

drop policy if exists api_keys_business_read on public.api_keys;
create policy api_keys_business_read on public.api_keys
for select using (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true)
);

drop policy if exists api_keys_business_update on public.api_keys;
create policy api_keys_business_update on public.api_keys
for update using (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true and role in ('owner', 'admin'))
) with check (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true and role in ('owner', 'admin'))
);

-- API usage for fixed-window rate limiting. The API Edge Function writes this
-- with the service role. Limit enforced in code: 100 requests/minute/key.
create table if not exists public.api_usage (
  id uuid primary key default gen_random_uuid(),
  api_key_id uuid references public.api_keys(id) on delete cascade,
  api_key text,
  count integer not null default 0,
  window_start timestamptz not null default date_trunc('minute', now()),
  created_at timestamptz not null default now()
);

alter table public.api_usage
  add column if not exists api_key_id uuid references public.api_keys(id) on delete cascade;

alter table public.api_usage
  alter column api_key drop not null,
  alter column count set default 0,
  alter column window_start set default date_trunc('minute', now());

create index if not exists idx_api_usage_key_window on public.api_usage(api_key_id, window_start desc);
create unique index if not exists api_usage_api_key_id_window_uidx on public.api_usage(api_key_id, window_start) where api_key_id is not null;

-- Webhook subscriptions and delivery log.
create table if not exists public.webhooks (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.businesses(id) on delete cascade,
  url text not null check (url ~* '^https://'),
  events text[] not null default '{}',
  secret text not null default encode(gen_random_bytes(32), 'hex'),
  is_active boolean not null default true,
  last_triggered_at timestamptz,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_webhooks_business_active on public.webhooks(business_id, is_active);
create index if not exists idx_webhooks_events on public.webhooks using gin(events);

alter table public.webhooks enable row level security;

drop policy if exists webhooks_business_read on public.webhooks;
create policy webhooks_business_read on public.webhooks
for select using (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true)
);

drop policy if exists webhooks_business_insert on public.webhooks;
create policy webhooks_business_insert on public.webhooks
for insert with check (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true and role in ('owner', 'admin'))
);

drop policy if exists webhooks_business_update on public.webhooks;
create policy webhooks_business_update on public.webhooks
for update using (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true and role in ('owner', 'admin'))
) with check (
  business_id in (select business_id from public.business_users where user_id = auth.uid() and is_active = true and role in ('owner', 'admin'))
);

create table if not exists public.webhook_deliveries (
  id uuid primary key default gen_random_uuid(),
  webhook_id uuid not null references public.webhooks(id) on delete cascade,
  event text not null,
  payload jsonb not null,
  status_code integer,
  response_body text,
  attempt integer not null default 1,
  delivered_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_webhook_deliveries_webhook on public.webhook_deliveries(webhook_id, created_at desc);

alter table public.webhook_deliveries enable row level security;

drop policy if exists webhook_deliveries_business_read on public.webhook_deliveries;
create policy webhook_deliveries_business_read on public.webhook_deliveries
for select using (
  webhook_id in (
    select w.id
    from public.webhooks w
    join public.business_users bu on bu.business_id = w.business_id
    where bu.user_id = auth.uid() and bu.is_active = true
  )
);
