-- Keep an auditable, server-timestamped record of the terms accepted by a
-- business owner. The timestamp is generated by Postgres, never supplied by
-- the browser.

CREATE TABLE IF NOT EXISTS public.business_terms_acceptances (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  business_id UUID NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE RESTRICT,
  terms_version TEXT NOT NULL,
  accepted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (business_id, user_id, terms_version)
);

CREATE INDEX IF NOT EXISTS business_terms_acceptances_business_id_idx
  ON public.business_terms_acceptances (business_id);

COMMENT ON TABLE public.business_terms_acceptances IS
  'Server-timestamped audit record of Terms and Conditions acceptance by business owners.';

ALTER TABLE public.business_terms_acceptances ENABLE ROW LEVEL SECURITY;

-- Do not expose the acceptance ledger through direct table access. The RPC
-- below verifies the caller is the current business owner and writes a record
-- using the database clock.
CREATE OR REPLACE FUNCTION public.record_business_terms_acceptance(
  p_business_id UUID,
  p_terms_version TEXT
)
RETURNS TIMESTAMPTZ
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_accepted_at TIMESTAMPTZ;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'You must be signed in to accept the Terms and Conditions.';
  END IF;

  IF p_terms_version <> '1.1' THEN
    RAISE EXCEPTION 'The supplied Terms and Conditions version is not current.';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM public.business_users
    WHERE business_id = p_business_id
      AND user_id = auth.uid()
      AND role = 'owner'
      AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Only an active business owner can record Terms and Conditions acceptance.';
  END IF;

  INSERT INTO public.business_terms_acceptances (business_id, user_id, terms_version)
  VALUES (p_business_id, auth.uid(), p_terms_version)
  ON CONFLICT (business_id, user_id, terms_version) DO UPDATE
    SET accepted_at = business_terms_acceptances.accepted_at
  RETURNING accepted_at INTO v_accepted_at;

  RETURN v_accepted_at;
END;
$$;

REVOKE ALL ON FUNCTION public.record_business_terms_acceptance(UUID, TEXT) FROM public;
GRANT EXECUTE ON FUNCTION public.record_business_terms_acceptance(UUID, TEXT) TO authenticated;
