import { useCallback, useEffect, useState } from 'react';
import { Loader2, Monitor, RefreshCw, ShieldX } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { AuthAlert } from './AuthUI';

type Session = { id:string; auth_session_id:string; device_name:string; browser:string; operating_system:string; location:string|null; last_seen_at:string; created_at:string };
const fn = (name:string) => `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/${name}`;
async function call(name:string, body?:unknown) { const {data}=await supabase.auth.getSession(); const r=await fetch(fn(name),{method:'POST',headers:{Authorization:`Bearer ${data.session?.access_token??''}`,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined}); const out=await r.json(); if(!r.ok) throw new Error(out.error??'Request failed'); return out; }
function browser(){const u=navigator.userAgent;return u.includes('Edg/')?'Edge':u.includes('Firefox/')?'Firefox':u.includes('Chrome/')?'Chrome':u.includes('Safari/')?'Safari':'Browser'}
function os(){const u=navigator.userAgent;return u.includes('Win')?'Windows':u.includes('Mac')?'macOS':u.includes('Android')?'Android':u.includes('iPhone')?'iOS':u.includes('Linux')?'Linux':'OS'}
export function SessionManager(){const [sessions,setSessions]=useState<Session[]>([]);const [currentId,setCurrentId]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [success,setSuccess]=useState('');
 const load=useCallback(async()=>{setLoading(true);try{const {data:auth}=await supabase.auth.getSession();const jwt=auth.session?.access_token;setCurrentId(jwt?JSON.parse(atob(jwt.split('.')[1].replace(/-/g,'+').replace(/_/g,'/'))).session_id??null:null);await call('register-session',{deviceName:`${browser()} on ${os()}`,browser:browser(),operatingSystem:os()});setSessions(await call('list-sessions'));setError(null)}catch(e){setError(String(e))}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const timer=setInterval(async()=>{try{const result=await call('validate-session');if(!result.valid){await supabase.auth.signOut({scope:'local'});window.location.assign('/login')}}catch{/* transient network errors must not log users out */}void call('touch-session')},300000);return()=>clearInterval(timer)},[load]);
 async function revoke(id:string){try{await call('revoke-session',{id});setSuccess('Session revoked.');await load()}catch(e){setError(String(e))}}
 if(loading&&!sessions.length)return <div className="flex gap-2 py-4 text-sm text-gray-500"><Loader2 className="animate-spin"/>Loading active sessions…</div>;
 return <div className="space-y-4">{error&&<AuthAlert type="error" message={error}/>} {success&&<AuthAlert type="success" message={success}/>} {sessions.map(s=><div key={s.id} className="flex items-center gap-3 rounded-xl border border-gray-200 p-4"><Monitor className="h-5 w-5 text-brand-600"/><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{s.browser} on {s.operating_system} {s.auth_session_id===currentId&&<span className="ml-2 rounded-full bg-brand-50 px-2 py-0.5 text-xs text-brand-700">Active</span>}</p><p className="text-xs text-gray-500">{s.location??'Location unavailable'} · Last active {new Date(s.last_seen_at).toLocaleString()}</p></div><button title="Revoke session" onClick={()=>void revoke(s.id)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><ShieldX className="h-4 w-4"/></button></div>)}<button onClick={()=>void load()} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><RefreshCw className="h-4 w-4"/>Refresh</button><p className="text-xs text-gray-500">Revocation is checked by Ledgr’s session API and takes effect when the device next validates its session.</p></div>}
